# Generated by Django 5.2.1 on 2025-05-30 18:45

import digitizer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarChartAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Analysis', max_length=255, verbose_name='Analysis Title')),
                ('original_image', models.ImageField(upload_to=digitizer.models.user_directory_path, verbose_name='Original Image')),
                ('analyzed_image', models.ImageField(blank=True, null=True, upload_to='analyzed/', verbose_name='Analyzed Image')),
                ('y1_position', models.IntegerField(verbose_name='Baseline Position')),
                ('y2_position', models.IntegerField(verbose_name='Reference Position')),
                ('value_difference', models.FloatField(verbose_name='Value Difference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('results_json', models.JSONField(blank=True, null=True, verbose_name='Results Data')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Confidence Score')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bar Chart Analysis',
                'verbose_name_plural': 'Bar Chart Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
