# Generated by Django 5.2.1 on 2025-05-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizer', '0002_remove_barchartanalysis_value_difference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchartanalysis',
            name='x1_position',
            field=models.IntegerField(null=True, verbose_name='Point 1 X Position'),
        ),
        migrations.AddField(
            model_name='barchartanalysis',
            name='x2_position',
            field=models.IntegerField(null=True, verbose_name='Point 2 X Position'),
        ),
        migrations.AlterField(
            model_name='barchartanalysis',
            name='y1_position',
            field=models.IntegerField(null=True, verbose_name='Point 1 Y Position'),
        ),
        migrations.AlterField(
            model_name='barchartanalysis',
            name='y2_position',
            field=models.IntegerField(null=True, verbose_name='Point 2 Y Position'),
        ),
    ]
