# Generated by Django 5.2.1 on 2025-06-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitizer', '0003_barchartanalysis_x1_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barchartanalysis',
            old_name='y1_value',
            new_name='p1_value',
        ),
        migrations.RenameField(
            model_name='barchartanalysis',
            old_name='y2_value',
            new_name='p2_value',
        ),
    ]
